### ISSUE TITLE
The first time step is skipped in the flo-2d results

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#197]
The first time step in the flo-2d results seems to have been omitted. None of the files I have checked contains output time at 00:00:00.

**Comment by PeterPetrik** [comment]
there is no 0.00 time in TIMDEP.OUT file. Wondering where the 00:00:00 time is?

**Comment by PeterPetrik** [comment]
Confirmed from FLO-2D team that TIMDEP.OUT does not have output for time 0.

**Comment by PeterPetrik** [comment]
Fortunately, even in software development issues sometimes are solved itself...

---------

Revision note: "195. The TIMDEP.OUT file was revised to include a zero time output interval with all zeros for all reported values, so that the various plots made this file have an initial zero starting point.  Previously, the first set of reported data was the first nonzero output interval (5/21/16).  Build No. 16-02-14. "

The previous versions of build 16-02-14 will not have the 0 timestep.
